# Generated by Django 3.0.8 on 2021-07-01 13:07

from django.db import migrations
from catalog_system.constants import Roles


def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for role_name in Roles:
        Group.objects.get_or_create(name=role_name)


def rollback(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.RunPython(create_roles, rollback),
    ]
