# Generated by Django 3.0.8 on 2021-08-03 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_system", "0001_roles_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("brand", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
